export const CONSTANTS = {
  URL: {
    BASE_URL:
      "https://dancewithme-b9gadtdhbjdya5c5.westus-01.azurewebsites.net",
    // BASE_URL: "",
    LOGIN: "/api/v1/admin/login",
    UPLOAD_MEDIA: "/api/v1/file/upload",
    DASHBOARD: "/dashboard",
    PROFILE: "/profile",
    USERS: "/users",
    GET_PROGRAMS: "/api/v1/admin/program",
    CREATE_PROGRAM: "/api/v1/admin/program",
    GET_CHALLENGES: "/api/v1/admin/challenge?page=1&limit=20",
    CHALLENGE_CREATE: "/api/v1/admin/challenge",
    APPROVE_INSTRUCTOR: "/api/v1/admin/approveInstructorApplication",
    REJECT_INSTRUCTOR: "/api/v1/admin/rejectInstructorApplication",
    INSTRUCTOR_APPLICATION_LIST: "/api/v1/admin/instructorApplicationList",
    APPROVE_ORGANIZER: "/api/v1/admin/approveOrganiserApplication",
    REJECT_ORGANIZER: "/api/v1/admin/rejectOrganiserApplication",
    ORGANIZER_APPLICATION_LIST: "/api/v1/admin/organiserApplicationList",
    APPROVE_DJ: "/api/v1/admin/approveDjApplication",
    REJECT_DJ: "/api/v1/admin/rejectDjApplication",
    DJ_APPLICATION_LIST: "/api/v1/admin/djApplicationList",
    USERS_USER: "/api/v1/admin/users?userType=user&page=1&limit=10",
    USERS_DJ: "/api/v1/admin/users?userType=dj&page=1&limit=10",
    USERS_PROFESSOR: "/api/v1/admin/users?userType=instructor&page=1&limit=10",
    USERS_ORGANIZER: "/api/v1/admin/users?userType=organiser&page=1&limit=10",
  },
};
